### ISSUE TITLE
something wrong with autocomplete menu (pmenu) colors

### ISSUE THREAD

**Issue by stobenski** [whatyouhide/vim-gotham#20] opened 2015-09-22 09:04 UTC
I use iTerm2 + [Gotham.itermcolors](https://github.com/whatyouhide/gotham-contrib/blob/master/iterm2/Gotham.itermcolors) + [gotham.vim](https://github.com/whatyouhide/vim-gotham/blob/master/colors/gotham.vim) and trying to <kbd>C-x</kbd> <kbd>C-l</kbd> or <kbd>C-x</kbd> <kbd>C-o</kbd> or just neocomplete/YCM menu invocation:
![](http://i.imgur.com/LZMhiNg.png)
Vim 7.4.865

**Comment by whatyouhide** [comment] 2015-09-22 11:09
@barwinko hey, thanks for the report. How long ago did you clone the iTerm 2 colorscheme? I updated a color a couple of days ago and that may be what's causing the issue.

**Comment by barwinko** [comment] 2015-09-22 14:24
2015 . Sep 21 . 23:25

**Comment by lmarlow** [comment] 2016-09-26 17:38
I am seeing this as well. I just switched to gotham last week, about a year after this report. @stobenski, did you find a workaround?

**Comment by stobenski** [comment] 2016-09-26 17:44
@lmarlow no, I switched to [base16-grayscale](http://i.imgur.com/pDHNN7E.png) colorscheme.

**Comment by whatyouhide** [comment] 2016-09-26 18:58
Hey, I'm on vacation and will be for the next month or so. Maybe you can try exploring this a bit yourself and maybe submit a PR with a fix? :D that would be awesome! 💟

**Comment by lmarlow** [comment] 2016-09-26 22:02
This seems to be terminal related. It looks great in the GUI. I usually use neovim within tmux in iTerm2. TERM reports `screen-256color` and iTerm is set to report the terminal as . I'm using the Gotham.itermcolors theme. I will see if I can come up with a solution that works well for me.

**Comment by whatyouhide** [comment] 2016-09-26 22:04
@lmarlow 💟

**Comment by whatyouhide** [comment] 2017-01-21 23:59
@lmarlow any news?

**Comment by lmarlow** [comment] 2017-01-23 19:30
@whatyouhide, I can't seem to reproduce it now. I had tweaked some colors initially to get over the hump. I just deleted my preset and reimported Gothm.itermcolors. It now looks like 
![image](https://cloud.githubusercontent.com/assets/628/22219296/722ef63c-e167-11e6-8ec0-5d6ce9facfac.png)

It's still too light for me on the menu, but I may try ergo or stable. Is there any difference between the 2?

Here's stable:
![image](https://cloud.githubusercontent.com/assets/628/22219339/a8eb8064-e167-11e6-8e6e-454a9181db2c.png)

This is all neovim inside a tmux pane.

Sorry for not getting back to you about this.

**Comment by whatyouhide** [comment] 2017-01-24 08:52
@lmarlow I don't even remember, I know that "ergo" wasn't written by me, and as far as I remember (it's been years), "stable" was just related to the iTerm version? I'm not sure, but since "stable" seems to work nice for you, I will just close this issue. Feel free to ping here again if you still have problems :).

**Closed by whatyouhide** 2017-01-24 08:52 UTC

**Comment by alexanderjeurissen** [comment] 2017-02-06 08:00
Just to chime in here regarding the different versions:
Ergo was created by me and is a version that increases and reduces the contrast of some colors. see PR: https://github.com/whatyouhide/gotham-contrib/pull/18
