### ISSUE TITLE
AirlineTheme does not applied on launch Vim

### ISSUE THREAD

**Issue by 0xBADDCAFE** [whatyouhide/vim-gotham#35] opened 2017-02-10 07:34 UTC
From: 4507f9d47e51270b12bc693ad13e66aa646c3880
Version: VIM - Vi IMproved 8.0.297 (on OS X from [here](https://github.com/splhack/macvim-kaoriya/releases)), VIM - Vi IMproved 7.3 (on OS X default CUI)

Problem
======

Launch Vim with `vim -u NORC -N --cmd "set ls=2" --cmd "set runtimepath+=~/.vim/bundle/vim-airline,~/.vim/bundle/vim-gotham" --cmd "colorscheme gotham256"` (This only load airline and gotham) AirlineThene does not applied automatic on launch. Before 4507f9d47e51270b12bc693ad13e66aa646c3880, it applied.

Erase near L88-99 in autoload/airline/themes/gotham256.vim, it does not occur. But I don't know how to fix these lines.

**Comment by taylorking** [comment] 2017-02-10 16:02
+1. I'm encountering this issue as well

**Comment by whatyouhide** [comment] 2017-02-10 16:11
@alexanderjeurissen could this be caused by your recent changes?

**Comment by alexanderjeurissen** [comment] 2017-02-10 18:57
@whatyouhide Could be I'll try to reproduce this error.

@0xBADDCAFE could you elaborate what lines you removed you said near 88-99 do you mean the code in the range 88-99 ? or code above or below it ?

**Comment by taylorking** [comment] 2017-02-10 19:06
commenting out these lines 

```
" Colors.
"let s:R1 = s:Array('base2', 'orange')
"let s:R2 = s:Array('base6', 'base3')
"let s:R3 = s:Array('base4', 'base1')

"let g:airline#themes#gotham#palette.replace =
"      \ airline#themes#generate_color_map(s:R1, s:R2, s:R3)

" Overrides for when the buffer is modified in normal mode.
"let g:airline#themes#gotham#palette.replace_modified = {
"     \ 'airline_c': s:Array('magenta', 'base1', '')
"      \ }

``` 

fixes the issue

**Comment by 0xBADDCAFE** [comment] 2017-02-12 10:49
> you said near 88-99 do you mean the code in the range 88-99 ? or code above or below it ?
Range 88-99 as said @taylorking . "Near" points misalignment position if adding more commits in file.

**Comment by alexanderjeurissen** [comment] 2017-02-21 21:13
Sorry for not responding sooner, I blocked some time in the coming weekend to solve this.

**Comment by whatyouhide** [comment] 2017-05-14 13:23
@alexanderjeurissen ping?

**Comment by whatyouhide** [comment] 2017-08-13 19:32
@alexanderjeurissen ping?

**Comment by alexanderjeurissen** [comment] 2017-08-27 05:48
@whatyouhide I don't expect to have the time to look into this in the near term. At the moment I'm too occupied with other projects. In addition, I'm not using airline nor am I currently using vim-gotham.

**Comment by whatyouhide** [comment] 2017-10-06 13:11
@0xBADDCAFE @taylorking hey folks, since @alexanderjeurissen dropped out of this, I am going to close this issue as I don't have time to work on it. If any of you feels like exploring this a little deeper to try and find out what's wrong, please feel free to do so and comment here if you find anything interesting :).

**Closed by whatyouhide** 2017-10-06 13:11 UTC
