### ISSUE TITLE
[ruby] function names, keywords and variable names are all the same color

### ISSUE THREAD

**Issue by rebebop** [whatyouhide/vim-gotham#61] opened 2021-12-01 13:13 UTC
Hi,
I'm having this problem in ruby where all function names and keywords are all the same color. I think the function names ought to be brighter. I'm using latest kitty terminal with neovim.

<img width="466" alt="Screenshot 2021-12-01 at 16 11 12" src="https://user-images.githubusercontent.com/1941785/144240537-0ab37a32-6afa-4833-a6d9-7671c32787fb.png">

**Comment by whatyouhide** [comment] 2021-12-01 17:48
Hey @rebebop, some language in some editor in some terminal is always gonna be weird with colorschemes. If you find a way to fix this, contributions are more than welcome! In the meantime, I'll close this issue since I'm not gonna be able to spend time reproducing, investigating, and potentially fixing. Thanks for the report! 💟

**Closed by whatyouhide** 2021-12-01 17:48 UTC

**Comment by rebebop** [comment] 2021-12-02 16:47
@whatyouhide no problem, but would be helpful if you can also point me in the direction of how I can being to debug this as I have never really made any vim theme/plugin. :)

**Comment by whatyouhide** [comment] 2021-12-13 12:35
@rebebop I'm sorry to say that I have no knowledge of that anymore, I haven't used vim in a few years 😅
