### ISSUE TITLE
Buffer name text too dark

### ISSUE THREAD

**Issue by aalvarado** [whatyouhide/vim-gotham#38] opened 2017-03-22 16:14 UTC
Changes introduced here: https://github.com/whatyouhide/vim-gotham/pull/26

I feel that the text on the buffer name (tab file name) is too dark.

(with transparency)
![screen shot 2017-03-22 at 9 09 42 am](https://cloud.githubusercontent.com/assets/370322/24207819/2557fef8-0edf-11e7-88a5-1ea6deaaeeb8.png)

![screen shot 2017-03-22 at 9 10 28 am](https://cloud.githubusercontent.com/assets/370322/24207852/3d414c72-0edf-11e7-9485-6e071c407424.png)

Screenshot from the README:
<img width="1013" alt="687474703a2f2f692e696d6775722e636f6d2f4e66527548464e2e706e67" src="https://cloud.githubusercontent.com/assets/370322/24207952/86a3e00a-0edf-11e7-9f8f-eabe94326d58.png">

I feel the last screenshot shows better colors for filenames. Is this something that anyone else is experiencing?

I've been having a hard time switching through tabs since my brain takes a bit more to try and identify the filename, before it was very quick, now my eyes dance a bit around the tab to read the name.

thanks!

**Comment by whatyouhide** [comment] 2017-03-23 01:18
@alexanderjeurissen #23 did not include screenshots of the tab bar, is this change intended?

**Comment by alexanderjeurissen** [comment] 2017-03-23 01:43
@whatyouhide that was definitely not intended, I rarely used vim tabs back when I introduced that change and didn't test for this regression. I'll take a look this weekend.

**Comment by whatyouhide** [comment] 2017-03-23 01:44
@alexanderjeurissen awesome, thanks a lot 💟

**Comment by alexanderjeurissen** [comment] 2017-03-26 20:33
@whatyouhide Didn't get around to looking into this issue this weekend, I'll update this issue when I've come up with a fix.

**Comment by whatyouhide** [comment] 2017-06-27 07:50
Closed via #43.

**Closed by whatyouhide** 2017-06-27 07:50 UTC
